### ISSUE TITLE
failed to handle method call flutter error 

### ISSUE THREAD

**Issue by rashmisridar** [anilgsharma900/MethodChannelDemo#1]
After running the sample getting the error like 

E/MethodChannel#flutter/MethodChannelDemo(15187): Failed to handle method call
E/MethodChannel#flutter/MethodChannelDemo(15187): java.lang.NullPointerException: folder.listFiles() must not be null
E/MethodChannel#flutter/MethodChannelDemo(15187): 	at com.anidhisoftware.methodchannel_demo.MainActivity.configureFlutterEngine$lambda-0(MainActivity.kt:19)
E/MethodChannel#flutter/MethodChannelDemo(15187): 	at com.anidhisoftware.methodchannel_demo.MainActivity.lambda$5CiaAg0CjQb7PKBjL2EWkdZJnyI(Unknown Source:0)
E/MethodChannel#flutter/MethodChannelDemo(15187): 	at com.anidhisoftware.methodchannel_demo.-$$Lambda$MainActivity$5CiaAg0CjQb7PKBjL2EWkdZJnyI.onMethodCall(Unknown Source:0)
E/MethodChannel#flutter/MethodChannelDemo(15187): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter/MethodChannelDemo(15187): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#flutter/MethodChannelDemo(15187): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/MethodChannel#flutter/MethodChannelDemo(15187): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
E/MethodChannel#flutter/MethodChannelDemo(15187): 	at android.os.Handler.handleCallback(Handler.java:883)
E/MethodChannel#flutter/MethodChannelDemo(15187): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/MethodChannel#flutter/MethodChannelDemo(15187): 	at android.os.Looper.loop(Looper.java:230)
E/MethodChannel#flutter/MethodChannelDemo(15187): 	at android.app.ActivityThread.main(ActivityThread.java:7880)
E/MethodChannel#flutter/MethodChannelDemo(15187): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/MethodChannelDemo(15187): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
E/MethodChannel#flutter/MethodChannelDemo(15187): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
I/flutter (15187): exceptiong

**Comment by anilgsharma900** [comment]
It is resolved
